baseURL = "https://www.sg.ethz.ch/"
languageCode = "en-us"
title = "Chair of Systems Design"
theme = "eth-hugo"
relativeURLS = false
canonifyurls = true
pluralizelisttitles = "false"



[taxonomies]
    area = "areas"
    project = "projects"

[params]
    unitName = "Chair of Systems Design"
    unitCode = "SG"
    departmentCode = "D-MTEC"
    departmentURL = "https://mtec.ethz.ch/"
    maxFeaturedPosts = 9
    maxPinnedPosts = 3
    pubsInProfile = 15



[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2
  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 3
 # [[menu.main]]
 #   name = "Research"
 #   url = "/areas/"
 #   weight = 4
 [[menu.main]]
   name = "Projects"
   url = "/projects/"
   weight = 5
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 6
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 7
  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 8



[markup.goldmark.renderer]
    unsafe= true # this allows to use html in markdown files


pygmentsUseClasses = false

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
